cd win32
cd ..
cd wingui
cvs remove about2.cpp
cvs remove about2.h
cvs remove about.cpp
cvs remove about.h
cvs remove acctable.cpp
cvs remove acctable.h
cvs remove actionar.cpp
cvs remove actionar.h
cvs remove address.cpp
cvs remove address.h
cvs remove aliases.cpp
cvs remove aliases.h
cvs remove attacha.cpp
cvs remove attacha.h
cvs remove attachd.cpp
cvs remove attachd.h
cvs remove attachfr.cpp
cvs remove attachfr.h
cvs remove attachi.cpp
cvs remove attachi.h
cvs remove attach.typ
cvs remove attachu.cpp
cvs remove attachu.h
cvs remove bitmap.cpp
cvs remove bitmap.h
cvs remove browser.cpp
cvs remove browser.h
cvs remove btitem.cpp
cvs remove btitem.h
cvs remove btndlg.cpp
cvs remove btndlg.h
cvs remove btpanel.cpp
cvs remove btpanel.h
cvs remove button.cpp
cvs remove button.h
cvs remove catable.cpp
cvs remove catable.h
cvs remove catalog.pl
cvs remove chalias.cpp
cvs remove chalias.h
cvs remove childdlg.cpp
cvs remove childdlg.h
cvs remove choose1.cpp
cvs remove choose1.h
cvs remove clntdoc.cpp
cvs remove clntdoc.h
cvs remove clntobj.cpp
cvs remove clntobj.h
cvs remove cmdline.cpp
cvs remove cmdline.h
cvs remove colors.cpp
cvs remove colors.h
cvs remove combobox.cpp
cvs remove combobox.h
cvs remove compopts.cpp
cvs remove compopts.h
cvs remove compose.cpp
cvs remove compose.h
cvs remove confdata.cpp
cvs remove confdata.h
cvs remove confirm.cpp
cvs remove confirm.h
cvs remove convbuf.cpp
cvs remove convbuf.h
cvs remove custsort.cpp
cvs remove custsort.h
cvs remove datesrch.cpp
cvs remove datesrch.h
cvs remove dialogs.cpp
cvs remove dialogs.h
cvs remove edit.cpp
cvs remove edit.h
cvs remove envelope.cpp
cvs remove envelope.h
cvs remove faceicon.cpp
cvs remove faceicon.h
cvs remove filefndr.cpp
cvs remove filefndr.h
cvs remove filters.cpp
cvs remove filters.h
cvs remove fldrdata.cpp
cvs remove fldrdata.h
cvs remove fldrlabl.cpp
cvs remove fldrlabl.h
cvs remove fldrlist.cpp
cvs remove fldrlist.h
cvs remove fldrsel.cpp
cvs remove fldrsel.h
cvs remove fonts.cpp
cvs remove fonts.h
cvs remove frame.cpp
cvs remove framedb.cpp
cvs remove framedb.h
cvs remove frame.h
cvs remove framemgr.cpp
cvs remove framemgr.h
cvs remove framewnd.cpp
cvs remove framewnd.h
cvs remove funcs.cpp
cvs remove funcs.h
cvs remove gdidb.cpp
cvs remove gdidb.h
cvs remove global.h
cvs remove groupbox.cpp
cvs remove groupbox.h
cvs remove guiapi.cpp
cvs remove guiclass.cpp
cvs remove guiids.h
cvs remove guiitems.pl
cvs remove guiitems.txt
cvs remove hdrmgr.cpp
cvs remove hdrmgr.h
cvs remove hdrpmpt.cpp
cvs remove hdrpmpt.h
cvs remove headersd.cpp
cvs remove headersd.h
cvs remove icon.cpp
cvs remove icon.h
cvs remove labeltxt.cpp
cvs remove labeltxt.h
cvs remove listbox.cpp
cvs remove listbox.h
cvs remove locale.rc
cvs remove login.cpp
cvs remove login.h
cvs remove mainwin.cpp
cvs remove mainwin.h
cvs remove manager.cpp
cvs remove manager.h
cvs remove menud.cpp
cvs remove menud.h
cvs remove menures.h
cvs remove menus.cpp
cvs remove menus.h
cvs remove mfctb.cpp
cvs remove mfctb.h
cvs remove mklibs.sh
cvs remove msgfield.cpp
cvs remove msgfield.h
cvs remove msggrp.h
cvs remove msglabel.cpp
cvs remove msglabel.h
cvs remove msgport.h
cvs remove msgwin.cpp
cvs remove msgwin.h
cvs remove newarriv.cpp
cvs remove newarriv.h
cvs remove newfldr.cpp
cvs remove newfldr.h
cvs remove olebase.h
cvs remove openfldr.cpp
cvs remove openfldr.h
cvs remove ostream.cpp
cvs remove ostream.h
cvs remove output.cpp
cvs remove output.h
cvs remove pagerd.cpp
cvs remove pagerd.h
cvs remove pagerfr.cpp
cvs remove pagerfr.h
cvs remove palette.cpp
cvs remove palette.h
cvs remove panedw.cpp
cvs remove panedw.h
cvs remove parentcf.cpp
cvs remove parent.cpp
cvs remove parent.h
cvs remove parentsc.cpp
cvs remove patsrch.cpp
cvs remove patsrch.h
cvs remove printerd.cpp
cvs remove printerd.h
cvs remove prisel.cpp
cvs remove prisel.h
cvs remove prmptdlg.cpp
cvs remove prmptdlg.h
cvs remove rect.h
cvs remove renfldr.cpp
cvs remove renfldr.h
cvs remove resdata.cpp
cvs remove resdata.h
cvs remove ressrc.rc
cvs remove rowcol.cpp
cvs remove rowcol.h
cvs remove sash.cpp
cvs remove sash.h
cvs remove savemsg.cpp
cvs remove savemsg.h
cvs remove scriplst.cpp
cvs remove scriplst.h
cvs remove scrolwin.cpp
cvs remove scrolwin.h
cvs remove setbox.cpp
cvs remove setbox.h
cvs remove slider.cpp
cvs remove slider.h
cvs remove sock.cpp
cvs remove sock.h
cvs remove srchrep.cpp
cvs remove srchrep.h
cvs remove stamplibs.sh
cvs remove statbar.cpp
cvs remove statbar.h
cvs remove static.cpp
cvs remove static.h
cvs remove summries.cpp
cvs remove summries.h
cvs remove syncdlg1.cpp
cvs remove syncdlg1.h
cvs remove syncdlg2.cpp
cvs remove syncdlg2.h
cvs remove syncdlg3.cpp
cvs remove syncdlg3.h
cvs remove syncdlg4.cpp
cvs remove syncdlg4.h
cvs remove syncdlg5.cpp
cvs remove syncdlg5.h
cvs remove syncdlg6.cpp
cvs remove syncdlg6.h
cvs remove system.rc
cvs remove taskm.cpp
cvs remove taskm.h
cvs remove template.cpp
cvs remove template.h
cvs remove termwnd.cpp
cvs remove termwnd.h
cvs remove toggrp.cpp
cvs remove toggrp.h
cvs remove toolbar.cpp
cvs remove toolbar.h
cvs remove toolbarx.cpp
cvs remove toolbarx.h
cvs remove toolbox.cpp
cvs remove toolbox.h
cvs remove transtab.cpp
cvs remove transtab.h
cvs remove uucp.c
cvs remove variable
cvs remove varsd.cpp
cvs remove varsd.h
cvs remove vector.h
cvs remove wingui.h
cvs remove wingui.texinfo
cvs remove winitem.cpp
cvs remove winitem.h
cvs remove winsync.cpp
cvs remove winsync.h
cvs remove zdlgs.h
cvs remove zdlgs.rc
cvs remove zmail16.rc
cvs remove zmail16.rcv
cvs remove zmailmnu.rc
cvs remove zmapp.cpp
cvs remove zmapp.h
cvs remove zmrev.h
cd build
cvs remove features.h
cvs remove ico2ppm.c
cvs remove mkmak.sh
cvs remove osconfig.h
cvs remove ppm2ico.c
cd ../delphi
cd ../install
cvs remove install.rul
cd dll
cvs remove basedefs.h
cvs remove defids.h
cvs remove dirdlg.c
cvs remove dirdlg.h
cvs remove instd.c
cvs remove instd.def
cvs remove instd.h
cvs remove instd.rc
cvs remove makefile
cvs remove netdlg.c
cvs remove netdlg.h
cvs remove resource.h
cvs remove resrc1.h
cvs remove util.c
cvs remove util.h
cvs remove vardlg.c
cvs remove vardlg.h
cd ../../../winspell
cvs remove spell.rc
cvs remove spell.rcv
cvs remove spfunc.cpp
cvs remove spglob.cpp
cvs remove spglob.h
cvs remove spmain.cpp
cvs remove vtspell.h
cvs remove zspell16.def
cvs remove zspell16.mak
cvs remove zspell.h
cd ../wintext
cvs remove g_debug.c
cvs remove g_fmtstr.c
cvs remove rc_defs.h
cvs remove resource.h
cvs remove win32prt.h
cvs remove winfuncs.h
cvs remove win_main.c
cvs remove wintext1.c
cvs remove wintext2.c
cvs remove wintext2.h
cvs remove wintext3.c
cvs remove wintext3.h
cvs remove wtconfig.h
cvs remove z_txtwin.h
