#ifndef _MEMERR_H
#define _MEMERR_H

typedef enum
{
    MEM_NO_ERROR = 0,
    MEM_NOT_INITIALIZED,
    MEM_ALREADY_INITIALIZED,
    MEM_NULL_HANDLE,
    MEM_HANDLE_ACCESSED,
    MEM_HANDLE_NOT_ACCESSED,
    MEM_POS_GREATER_THAN_SIZE,
    MEM_MIN_GREATER_THAN_MAX,
    MEM_MIN_GREATER_THAN_SIZE,
    MEM_CANT_ACCESS,
    MEM_BAD_ACCESS_MODE,
    MEM_BAD_SEEK_MODE,
    MEM_BAD_ABSOLUTE_OFFSET,
    MEM_ALLOC_FAILED,
    MEM_NOT_ENOUGH_MEMORY,
    MEM_CANT_CREATE_HANDLE,
    MEM_CANT_CREATE_MEMINFO,
    MEM_MEMORY_NOT_AVAILABLE,
    MEM_BAD_DIRECTION,
    MEM_BAD_RELATIVE_OFFSET,
    MEM_NOT_COMPLEX_HANDLE
} MEM_ERROR;

#endif /* _MEMERR_H */
