cd mac
rm BuildNotes
rm Distribution-Steps
rm KnownBugs
rm type-reg.txt
cd ..
cd mac/catrsrc
rm catrsrc.c
rm catrsrc.h
rm catrsrc.make
rm catrsrc.r
cd ../..
cd mac/c-mac
rm binhex.c
rm binhex.h
rm configuration.cp
rm configuration.h
rm connection.c
rm dialogs.c
rm environ.c
rm environ.h
rm gui_stuff.c
rm GUSI-glue.cp
rm hostname.c
rm initialization.c
rm mac-stuff.h
rm mac-unix.c
rm new_fopen.c
rm prepfile.c
rm prepfile.h
rm registration.c
rm SFGray.c
rm SFGray.r
rm stubs.c
rm zmlib.c
rm zmprint-mac.c
rm zmprint-mac.h
rm ztimer.c
rm zxdialog.h
cd ../..
cd mac/config-mac
rm config.h
rm defaults.h
rm features.h
rm macintosh.h
rm maxsig.h
rm osconfig.h
rm os-mac.h
rm sigarray.h
rm signames.h
cd ../..
cd mac/cplus-mac
rm gui_api.cp
rm Misc.cp
rm MZMail.cp
rm rsrc_strings.h
rm UAliases.cp
rm UAttachments.cp
rm UAttachments.h
rm UButtons.cp
rm UButtons.h
rm UCompFrame.cp
rm UCompFrame.h
rm UControlStuff.cp
rm UControlStuff.h
rm UDialogs.cp
rm UDialogs.h
rm UDlogFilters.cp
rm UDlogFunctions.cp
rm UDlogSearch.cp
rm UDlogSort.cp
rm UDocClass.h
rm UFolderFrame.cp
rm UFolderFrame.h
rm UFrame.cp
rm UFrame.h
rm UFrameParts.cp
rm UFrameParts.h
rm UGenericDialog.cp
rm UGenericDialog.h
rm UHelp.cp
rm UKid.cp
rm UKid.h
rm UMACommand.cp
rm UMACommand.h
rm UMenuStuff.cp
rm UMsgFrame.cp
rm UMsgFrame.h
rm UPageFrame.cp
rm UPageFrame.h
rm UTaskMeter.cp
rm UTextEdit.cp
rm UTitleText.cp
rm UTitleText.h
rm UUtils.cp
rm UVariables.cp
rm UVariables.h
rm UZMApp.cp
rm UZMApp.h
rm UZMConsts.h
rm UZMWindow.cp
rm UZMWindow.h
rm ZMail.MAMake
rm ZMail.r
rm ZmMenudialogs.cp
rm ZmPaging.cp
rm ZmStdFile.cp
cd ../..
cd mac/gusi
rm Aliases
rm Distribute
rm Distribution-Steps
rm _etc_services
rm GUSI_Appletalk.cfg
rm GUSIAppleTalk.cp
rm GUSIBuffer.cp
rm GUSI_C.dn
rm GUSICfg.c
rm GUSICfrg.r
rm GUSIDispatch.cp
rm GUSI.distr
rm GUSI.dn
rm GUSI_Everything.cfg
rm GUSI.ext
rm GUSIFile.cp
rm GUSIFileDispatch.cp
rm GUSIFSp.cp
rm GUSIINET.cp
rm GUSIINETd.cp
rm GUSI_Internet.cfg
rm GUSIMPWFile.cp
rm GUSIMPWGlue.cp
rm GUSINetDB.cp
rm GUSI_PAP.cfg
rm GUSIPAP.cp
rm GUSI_PPC.cfg
rm GUSIPPC.cp
rm GUSI.ps
rm GUSI.r
rm GUSIRemoteConsole.cp
rm GUSI.rsrc
rm GUSISIOW.cp
rm GUSISocket.cp
rm GUSITCP.cp
rm GUSI.tex
rm GUSIUDP.cp
rm GUSI_Unix.cfg
rm GUSIUnix.cp
rm GUSI.web
rm Internalize
rm KnownBugs
rm MakeAliases
rm Makefile
rm README
rm ReleaseBugs
rm SafeDel
rm SafeInstall
rm SetZVars
rm UserStartup_ZMail
cd ../..
cd mac/gusi/Examples
rm GUSIAtlkTest.c
rm GUSIAtlkTest.c.txt
rm GUSIFileTest.c
rm GUSIFileTest.c.txt
rm GUSIFinger.c
rm GUSIFinger.c.txt
rm GUSIFinger.r
rm GUSIFinger.r.txt
rm GUSIINETTest.c
rm GUSIINETTest.c.txt
rm GUSIPAPTest.c
rm GUSIPAPTest.c.txt
rm GUSIPPCTest.c
rm GUSIPPCTest.c.txt
rm GUSISocketTest.c
rm GUSISocketTest.c.txt
rm GUSITest.c
rm GUSITest.c.txt
rm GUSITest.h
rm GUSITest.h.txt
rm GUSITest_P.h
rm GUSITest_P.h.txt
rm GUSITest.r
rm GUSITest.rsrc
rm GUSITest.r.txt
rm GUSIUnixTest.c
rm GUSIUnixTest.c.txt
rm GUSIUnixTest.r
rm GUSIUnixTest.r.txt
rm Makefile
rm Makefile.txt
cd ../../..
cd mac/gusi/include
rm compat.h
rm dirent.h
rm GUSIFile_P.h
rm GUSI.h
rm GUSIINET_P.h
rm GUSIMPW_P.h
rm GUSI_P.h
rm GUSIPPC_P.h
rm GUSIRsrc_P.h
rm machine:2Fansi.h
rm machine:2Fendian.h
rm machine:2Ftypes.h
rm machine_ansi.h
rm machine_endian.h
rm machine_types.h
rm netdb.h
rm netinet:2Fin.h
rm netinet:2Ftcp.h
rm netinet_in.h
rm netinet_tcp.h
rm sys:2Fcdefs.h
rm sys:2Ferrno.h
rm sys:2Ffcntl.h
rm sys:2Fioctl.h
rm sys:2Fsocket.h
rm sys:2Fstat.h
rm sys:2Ftime.h
rm sys:2Ftypes.h
rm sys:2Fuio.h
rm sys:2Fun.h
rm sys:2Funistd.h
rm sys_cdefs.h
rm sys_errno.h
rm sys_fcntl.h
rm sys_ioctl.h
rm sys_socket.h
rm sys_stat.h
rm sys_time.h
rm sys_types.h
rm sys_uio.h
rm sys_un.h
rm sys_unistd.h
rm TFileSpec.h
rm unistd.h
rm utime.h
cd ../../..
cd mac/includes-mac
rm AddressXlation.h
rm dirserv.seg
rm general.seg
rm GetMyIPAddr.h
rm MacTCPCommonTypes.h
rm MiscIPPB.h
rm sh4seg.seg
rm TCP.h
rm TCPPB.h
rm UDPPB.h
rm zminit.seg
cd ../..
cd mac/lib
rm attach.types
rm command.hlp
rm locale.zmailrc
rm mac.hlp
rm README.mac-lib
rm sample.lib
rm system.zmailrc
rm variables
rm welcome
rm zmail.menus
cd ../..
cd mac/mac-utils/PerfTests
rm ftell_test.c
rm ftell_test.make
rm testio.c
rm testio.make
rm testseg.c
rm testseg.make
cd ../../..
cd mac/mac-utils/proclister
rm proclister.c
rm proclister.make
cd ../../..
cd mac/mac-utils/strftime
rm strftime.c
rm strftime.make
cd ../../..
cd mac/rsrc
rm resource.h
rm SleepZacur.r
rm ZMail.r
rm ZMAliasViews.r
rm ZMAskViews.r
rm ZMBalloons.r
rm ZMCompViews.r
rm ZMDialogs.r
rm ZMFilterViews.r
rm ZMGraphics.r
rm ZMHeaderViews.r
rm ZMLibFallbacks.r
rm ZMMainViews.r
rm ZMMenus.r
rm ZMMsgViews.r
rm ZMOtherViews.r
rm ZMReztypes.r
rm ZMSearchViews.r
rm ZMStrings.r
rm ZMVarViews.r
rm ZMViews.r
cd ../..
cd mac/scripts
rm automount
rm buildcontrol
rm builder.sh
rm difftrees
rm remotebuild
rm setCIncludes
rm SetZVars
rm UserStartup:A5ZMail
rm waitforproc
cd ../..
cd mac/talker
rm Makefile
rm talker.c
cd ../..
cd mac/transport
rm ASR.c
rm dnr.c
rm macsock.c
rm myTCPPB.c
cd ../..
