cvs remove compat.h
cvs remove dirent.h
cvs remove machine:2Fansi.h
cvs remove machine:2Fendian.h
cvs remove machine:2Ftypes.h
cvs remove netdb.h
cvs remove netinet:2Fin.h
cvs remove netinet:2Ftcp.h
cvs remove sys:2Fcdefs.h
cvs remove sys:2Ferrno.h
cvs remove sys:2Ffcntl.h
cvs remove sys:2Fioctl.h
cvs remove sys:2Fsocket.h
cvs remove sys:2Fstat.h
cvs remove sys:2Ftime.h
cvs remove sys:2Ftypes.h
cvs remove sys:2Fuio.h
cvs remove sys:2Fun.h
cvs remove sys:2Funistd.h
cvs remove unistd.h
cvs remove utime.h
