rm compat.h
rm dirent.h
rm machine:2Fansi.h
rm machine:2Fendian.h
rm machine:2Ftypes.h
rm netdb.h
rm netinet:2Fin.h
rm netinet:2Ftcp.h
rm sys:2Fcdefs.h
rm sys:2Ferrno.h
rm sys:2Ffcntl.h
rm sys:2Fioctl.h
rm sys:2Fsocket.h
rm sys:2Fstat.h
rm sys:2Ftime.h
rm sys:2Ftypes.h
rm sys:2Fuio.h
rm sys:2Fun.h
rm sys:2Funistd.h
rm unistd.h
rm utime.h
