cvs remove hostserv.c
cvs remove hostserv.h
cvs remove lsnetw.c
cvs remove access.c
cvs remove access.h
cvs remove client.h
cvs remove den.c
cvs remove den.h
cvs remove enter.c
cvs remove enter.h
cvs remove error.c
cvs remove foo.sh
cvs remove hosterr.h
cvs remove InstallNLS.txt
cvs remove library.c
cvs remove library.h
cvs remove local.mk
cvs remove lscustom.c
cvs remove lscustom.h
cvs remove lsfile.c
cvs remove lsfile.h
cvs remove lsutil.c
cvs remove lsutil.h
cvs remove Makefile
cvs remove netstuff.c
cvs remove onelice.c
cvs remove other.c
cvs remove register
cvs remove register.c
cvs remove register.h
cvs remove reg_main.c
cvs remove server.h
cvs remove servlib.c
cvs remove servlibS.c
cvs remove ver_date.c
cvs remove zcnlsd
cvs remove zcnltest.c
cvs remove zserver.c
cd zenter
cvs remove fallback.h
cvs remove gui_api.c
cvs remove gui_def.h
cvs remove Makefile
cvs remove mallocv.c
cvs remove m_api.c
cvs remove m_menus.c
cvs remove m_misc.c
cvs remove m_prompt.c
cvs remove tblwidget
cvs remove vargs.h
cvs remove Zenter
cvs remove zenter.c
cvs remove zenter_io.c
cd tblwidget
cvs remove Makefile
cvs remove README
cvs remove Table.c
cvs remove Table.c.1.1
cvs remove Table.doc
cvs remove TableEx1.c
cvs remove TableEx2.c
cvs remove Table.h
cvs remove Table.H
cvs remove TableP.h
cvs remove unhance
cd unhance
cvs remove Table.c
